services:

  drupal:
    image: drupal:10-apache
    container_name: drupal
    restart: unless-stopped
    ports:
      - "8200:80"
    volumes:  
      - ./d_modules:/var/www/html/modules \
      - ./d_profiles:/var/www/html/profiles \
      - ./d_sites:/var/www/html/sites \
      - ./d_themes:/var/www/html/themes \
    depends_on:
      - drupaldb
    environment:
      HOST: drupaldb
      DBASE: drupal
      USER: user
      PASS: p4ssw0rd  
      
  drupaldb:
    image: mysql:latest
    container_name: drupaldb 
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_ROOT_PASSWORD: p4ssw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupalpma 
    restart: unless-stopped
    environment:
      PMA_HOST: drupaldb
      PMA_USER: user
      PMA_PASSWORD: p4ssw0rd
    ports:
      - "8080:80"
    depends_on:
      - drupaldb   
      
      
      
      
      
      
